config/routes.rb
# frozen_string_literal: true

# App routes
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'articles#index'

  resources :articles

  resource :wizard do
    get :step1
    get :step2
    get :step3

    post :validate_step
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# Модель статьи (новости)
class Article < ApplicationRecord
  AGE_GROUPS = %w[0+ 6+ 12+ 16+ 18+].freeze
  CATEGORIES = %w[Auto Health Finance Events].freeze

  # Принадлежит автору (пользователю в системе, который опубликовал)
  belongs_to :user

  enum age_group: AGE_GROUPS
  enum category: CATEGORIES

  validates :title, :source_title, :body, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
# frozen_string_literal: true

# Модель пользователя (Devise)
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Root controller (others inherit from this one)
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Контроллер новостных статей
class ArticlesController < ApplicationController
  # include Wicked::Wizard
  # steps :add_title_and_source, :add_body, :add_categories

  before_action :authenticate_user!, only: %i[new create destroy]
  before_action :set_article, only: %i[show destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    redirect_to step1_wizard_path
  end

  def create; end

  def destroy
    @article.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Article was successfuly deleted' }
      format.json { head :no_content }
    end
  end

  private

  def article_permitted_params
    params.permit :title, :body, :source_title, :source_url,
                  :category, :age_group
  end

  def set_article
    @article = Article.find params.dig(:id)
  end
end

app/controllers/wizards_controller.rb
# frozen_string_literal: true

class WizardsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_article_wizard, except: %i[validate_step]

  def validate_step
    current_step = params.dig(:current_step)

    @article_wizard = wizard_article_for_step(current_step)
    @article_wizard.article.attributes = article_wizard_params
    session[:article_attributes] = @article_wizard.article.attributes

    if @article_wizard.valid?
      next_step = wizard_article_next_step(current_step)
      create && return unless next_step

      redirect_to action: next_step
    else
      render current_step
    end
  end

  def create
    @article_wizard.article.user = current_user
    if @article_wizard.article.save
      session[:article_attributes] = nil
      redirect_to root_path, notice: 'Article succesfuly created!'
    else
      redirect_to({action: Wizard::Article::STEPS.first}, alert: 'There were a problems when creating an article!')
    end
  end

  def show; end

  private

  def load_article_wizard
    @article_wizard = wizard_article_for_step(action_name)
  end

  def wizard_article_next_step(step)
    Wizard::Article::STEPS[Wizard::Article::STEPS.index(step) + 1]
  end

  def wizard_article_for_step(step)
    raise InvalidStep unless step.in?(Wizard::Article::STEPS)

    "Wizard::Article::#{step.camelize}".constantize.new(session[:article_attributes])
  end

  def article_wizard_params
    params.require(:article_wizard).permit(:title, :body, :source_title, :source_url, :category, :age_group)
  end

  class InvalidStep < StandardError; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
  <%= label :article_title, "Title" %>
  <%= f.text_field :title %>

  <%= label :article_source_title, "Source" %>
  <%= f.text_field :source_title %>

  <%= label :article_source_url, "URL" %>
  <%= f.text_field :source_url %>

  <%= link_to 'Next' %>
<% end %>

app/views/articles/destroy.js.erb
$('.delete').bind('ajax:success', function() {
  $(this).closest('.card').fadeOut();
});

app/views/articles/index.html.erb
<div class="articles-list">
  <% @articles.each do |article| %>
    <div class="card m-3">
      <div class="card-header">
        <%= article.created_at.strftime("%Y-%m-%d") %> <span class="text-muted">by <%= article.user.email %></span>
      </div>
      <div class="card-body">
        <div class="d-flex align-items-center justify-items-center">
          <h1><%= link_to article.title, article, class: "card-title" %></h1>
          <span class="text-muted italic ml-2">in category <%= article.category %></span>
        </div>
        <% if current_user.present? && current_user == article.user %>
          <%= link_to 'Delete', article_path(article),
                      method: :delete,
                      data: {confirm: 'Are you sure?', remote: true},
                      class: "btn btn-danger delete" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<% if @article.present? %>
  <div class="row justify-items-start align-items-end">
    <h1 class="mr-3 col-xm-2 align-self-center"><%= @article.title %></h1>
    <div class="col-xm-10">
      <p class="text-muted">
        added by <%= @article.user.email %> at <%= @article.user.created_at.strftime("%Y-%m-%d") %>
      </p>
      <p class="text-muted">
        <i>
          Category:
          <%= @article.category %>
          from <%= link_to @article.source_title, @article.source_url, class: "text-primary" %>
        </i>
        (<%= @article.age_group %>)
      </p>
    </div>
  </div>

  <p>
    <%= @article.body %>
  </p>
  
<% end %>

<%= link_to '<< Back', articles_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metastudio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# BOOTSTRAP NAVBAR TEMPLATE %>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to 'MetaStudio Test Task', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <% if current_user.present? %>
            <li class="nav-item">
              <%= link_to 'Add article +', new_article_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

        <% if current_user.present? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        <% end %>
      </div>
    </nav>
    <%# BOOTSTRAP NAVBAR TEMPLATE %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/wizards/step1.html.erb
<ol class="breadcrumb">
  <li class='active'>Step 1</li>
</ol>

<%= simple_form_for @article_wizard, as: :article_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>
  <%= hidden_field_tag :current_step, 'step1' %>

  <%= f.input :title, class: 'form-control' %>

  <%= f.input :source_title, class: 'form-control' %>
  <%= f.input :source_url, class: 'form-control' %>

  <%= f.submit 'Continue', class: 'form-control btn btn-primary mt-2' %>
<% end %>

app/views/wizards/step2.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Step 1", step1_wizard_path %></li>
  <li class="breadcrumb-item active">Step 2</li>
</ol>

<%= simple_form_for @article_wizard, as: :article_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>
  <%= hidden_field_tag :current_step, 'step2' %>

  <%= f.input :body, as: :text, class: 'form-control' %>

  <%= f.submit 'Continue', class: 'form-control btn btn-primary mt-2' %>
<% end %>

app/views/wizards/step3.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Step 1", step1_wizard_path %></li>
  <li class="breadcrumb-item"><%= link_to "Step 2", step2_wizard_path %></li>
  <li class="breadcrumb-item active">Step 3</li>
</ol>

<%= simple_form_for @article_wizard, as: :article_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>
  <%= hidden_field_tag :current_step, 'step3' %>

  <%= f.input :category, collection: Article::CATEGORIES %>
  <%= f.input :age_group, collection: Article::AGE_GROUPS %>

  <%= f.submit 'Add article', class: 'btn btn-primary' %>
<% end %>